"use client"

import { Play, ExternalLink, Calendar, Eye } from "lucide-react"
import { useState, useEffect } from "react"
import Link from "next/link"
import Image from "next/image"

// Single featured video - ready for YouTube API integration
const featuredVideo = {
  id: "featured",
  title: "HAKBORREL 2024 - OFFICIAL AFTERMOVIE",
  description: "Experience the raw energy and underground spirit of our latest gathering. Watch the highlights from our most intense event yet.",
  youtubeId: "SOH49z-S0G0", // Updated with actual YouTube video ID
  duration: "4:32",
  views: "28K",
  publishedAt: "2024-01-15",
  // YouTube thumbnail URL - automatically generated by YouTube
  thumbnail: "https://img.youtube.com/vi/SOH49z-S0G0/hqdefault.jpg"
}

export function VideoSection() {
  const [isHovered, setIsHovered] = useState(false)
  const [isVideoLoaded, setIsVideoLoaded] = useState(false)
  const [isClient, setIsClient] = useState(false)

  // Fix hydration issue by ensuring client-side rendering for date formatting
  useEffect(() => {
    setIsClient(true)
  }, [])

  const handleVideoClick = () => {
    if (!isVideoLoaded) {
      setIsVideoLoaded(true)
    } else {
      // Open in YouTube for better experience
      window.open(`https://www.youtube.com/watch?v=${featuredVideo.youtubeId}`, '_blank')
    }
  }

  // Format date safely for SSR
  const formatDate = (dateString: string) => {
    if (!isClient) return dateString // Return raw string during SSR
    return new Date(dateString).toLocaleDateString()
  }

  return (
    <section className="relative section-padding overflow-hidden">

      <div className="container-professional relative z-10 max-w-5xl">
        {/* Professional header */}
        <div className="text-center mb-20">
          <div className="inline-flex items-center gap-4 mb-8">
            <div className="w-1 h-12 bg-gradient-to-b from-primary to-primary/50"></div>
            <h2 className="text-5xl md:text-7xl font-display">
              <span className="text-white">FEATURED</span>{" "}
              <span className="text-gradient-primary">VIDEO</span>
            </h2>
            <div className="w-1 h-12 bg-gradient-to-b from-primary to-primary/50"></div>
          </div>
          <p className="text-gray-300 text-xl max-w-3xl mx-auto leading-relaxed font-body">
            Watch our latest aftermovie and experience the underground hardcore movement.
          </p>
        </div>

        {/* Professional video player */}
        <div className="max-w-4xl mx-auto">
          <div
            className="group relative aspect-video overflow-hidden rounded-xl border border-gray-700/50 hover:border-primary/50 transition-all duration-500 cursor-pointer bg-gray-900/50 backdrop-blur-smooth hover-lift"
            onMouseEnter={() => setIsHovered(true)}
            onMouseLeave={() => setIsHovered(false)}
            onClick={handleVideoClick}
          >
            {!isVideoLoaded ? (
              <>
                {/* YouTube thumbnail */}
                <Image
                  src="https://img.youtube.com/vi/SOH49z-S0G0/hqdefault.jpg"
                  alt={featuredVideo.title}
                  fill
                  className="object-cover transition-transform duration-700 group-hover:scale-105"
                />

                {/* Professional overlay */}
                <div className="absolute inset-0 bg-gradient-to-t from-black/80 via-black/20 to-transparent" />

                {/* Play button */}
                <div className="absolute inset-0 flex items-center justify-center">
                  <div
                    className={`w-20 h-20 rounded-full flex items-center justify-center transition-all duration-500 ${
                      isHovered ? "bg-primary scale-110 shadow-[0_0_40px_rgba(57,255,20,0.6)]" : "bg-primary/90 shadow-[0_0_20px_rgba(57,255,20,0.4)]"
                    }`}
                  >
                    <Play className="h-8 w-8 text-black fill-black ml-1" />
                  </div>
                </div>

                {/* Video info */}
                <div className="absolute bottom-0 left-0 right-0 p-6">
                  <h3 className="text-white font-bold text-xl md:text-2xl mb-2">{featuredVideo.title}</h3>
                  <p className="text-gray-300 text-sm md:text-base mb-3 line-clamp-2">{featuredVideo.description}</p>
                  <div className="flex items-center gap-4 text-sm text-gray-400">
                    <span className="flex items-center gap-1">
                      <Play className="h-3 w-3" />
                      {featuredVideo.duration}
                    </span>
                    <span>•</span>
                    <span className="flex items-center gap-1">
                      <Eye className="h-3 w-3" />
                      {featuredVideo.views} views
                    </span>
                    <span>•</span>
                    <span className="flex items-center gap-1" suppressHydrationWarning>
                      <Calendar className="h-3 w-3" />
                      {formatDate(featuredVideo.publishedAt)}
                    </span>
                  </div>
                </div>

                {/* Duration badge */}
                <div className="absolute top-4 right-4 bg-black/80 px-3 py-1 rounded-md text-white text-sm font-medium backdrop-blur-sm">
                  {featuredVideo.duration}
                </div>

                {/* YouTube branding */}
                <div className="absolute top-4 left-4 bg-red-600 px-3 py-1 rounded-md text-white text-xs font-bold flex items-center gap-1 backdrop-blur-sm">
                  <ExternalLink className="h-3 w-3" />
                  YouTube
                </div>
              </>
            ) : (
              /* Embedded YouTube video */
              <iframe
                width="100%"
                height="100%"
                src={`https://www.youtube.com/embed/${featuredVideo.youtubeId}?autoplay=1&rel=0`}
                title={featuredVideo.title}
                frameBorder="0"
                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                allowFullScreen
                className="w-full h-full"
              />
            )}
          </div>

          {/* Professional action section */}
          <div className="mt-12 text-center">
            <p className="text-gray-400 text-base mb-8 font-body">
              More videos coming soon. Subscribe to our channel for the latest content.
            </p>
            <div className="flex justify-center gap-6">
              <Link href="/tickets">
                <button className="btn-professional px-8 py-3 cursor-pointer">
                  GET TICKETS
                </button>
              </Link>
              <button className="btn-professional btn-secondary px-8 py-3 cursor-pointer">
                SUBSCRIBE
              </button>
            </div>
          </div>
        </div>
      </div>
    </section>
  )
}
